backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "index"
        file: "index.md"
        fields:
          - {label: Layout, name: layout, widget: hidden, default: index}
          - {label: Title, name: title, widget: string}
          - {label: Navigation, name: navigation, widget: hidden, default: Home}
          - {label: Description (SEO), name: description, widget: text}
          - {label: Background Video, name: background-asset, widget: file}
      - label: "Press"
        name: "press"
        file: "press.md"
        fields:
          - {label: Layout, name: layout, widget: hidden, default: press}
          - {label: Title, name: title, widget: string}
          - {label: Navigation, name: navigation, widget: hidden, default: News}
          - {label: Description (SEO), name: description, widget: text}
          - {label: Content, name: body, widget: markdown}

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    extension: "markdown"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title (Thumbnail)"
        name: "title"
        widget: "string"
      - label: "Title (Full)"
        name: "titleLong"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
      - label: "Navigation"
        name: "navigation"
        widget: "hidden"
        default: "Watch"
      - label: "Thumbnail"
        name: "image"
        widget: "image"
      - label: "Thumbnail Size"
        name: "emphasis"
        widget: "number"
        valueType: "int"
        min: 1
        max: 2
      - label: "Documentary, Animation or Series"
        name: "type"
        widget: "string"
      - label: "Article URL"
        name: "embedAtlantic"
        widget: "string"
      - label: "Embed Source URL"
        name: "embed"
        widget: "string"
      - label: "Awards"
        name: "awards"
        widget: "list"
        fields:
          - label: "Icon"
            name: "image"
            widget: "image"
      - label: "Description (SEO)"
        name: "description"
        widget: "text"
      - label: "Description (Full)"
        name: "body"
        widget: "markdown"
      - label: "Credits"
        name: "credits"
        widget: "list"
        fields:
          - label: "Role"
            name: "role"
            widget: "string"
          - label: "Name"
            name: "name"
            widget: "string"

  - name: "awards" # Used in routes, e.g., /admin/collections/blog
    label: "Awards" # Used in the UI
    folder: "_awards/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "md" # The file extension the CMS searches for
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Rank"
        name: "position"
        widget: "number"
        valueType: "int"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Details"
        name: "details"
        widget: "list"

  - name: "partners"
    label: "Partners"
    folder: "_partners"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Rank"
        name: "position"
        widget: "number"
        valueType: "int"

  - name: "people"
    label: "Staff"
    folder: "_people"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Name"
        name: "title"
        widget: "string"
      - label: "List Position"
        name: "position"
        widget: "number"
        valueType: "int"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Staff Page Link"
        name: "link"
        widget: "string"
      - label: "Role"
        name: "role"
        widget: "string"
